
title: Aiueokashi
author: Aiueokashi
email: unknown@github.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! It is Aiueokashi's pages

# social links
twitter_username: discord_PSekai # DO NOT include the @ character, or else the build will fail!
github_username:  Aiueokashi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
