
title: お菓子の日記
author: Aiueokashi
email: unknown@github.com
description: > # this means to ignore newlines until "baseurl:"
  お菓子の日記

# social links
twitter_username: discord_PSekai # DO NOT include the @ character, or else the build will fail!
github_username:  Aiueokashi # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
